name: Instagram to Telegram Forwarder

on:
  schedule:
    - cron: "*/35 * * * *"  # запуск каждые 5 минут
  # Можно добавить вручную запуск для тестирования
  workflow_dispatch:

jobs:
  insta_bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # даем право на push в репозиторий (для сохранения state)
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install instaloader==4.14.1 requests

      - name: Run Instagram bot script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
          ACCOUNTS: "account1, account2, account3"  # список аккаунтов через запятую
        run: python insta_telegram_bot.py

      - name: Commit updated state
        if: success()  # выполнять, только если предыдущий шаг успешен
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add state.json || true
          git add *.session || true
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update bot state [skip ci]"
            git push
          fi
